### ISSUE TITLE
panics when executing godoc example

### ISSUE THREAD

**Issue by natebrennand** [smartystreets/goconvey#223]
[Godoc examples](http://golang.org/src/pkg/net/http/example_test.go) fail to register with the package parser. When goconvey tries to execute the example code it [fails to find the test and panics](https://github.com/smartystreets/goconvey/blob/master/web/server/parser/packageParser.go#L97).

full stack trace

```
2014/07/09 14:20:29 executor.go:69: Executor status: 'idle'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x91dee]

goroutine 5 [running]:
runtime.panic(0x24ece0, 0x556039)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/panic.c:266 +0xb6
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).recordTestMetadata(0xc210118380)
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:104 +0x23e
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).processTestOutput(0xc210118380)
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:79 +0x90
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).separateTestFunctionsAndMetadata(0xc210118380)
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:47 +0x83
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).parse(0xc210118380)
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:38 +0x27
github.com/smartystreets/goconvey/web/server/parser.ParsePackageResults(0xc21008ca20, 0xc21003d380, 0x31c)
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:12 +0x49
github.com/smartystreets/goconvey/web/server/parser.(*Parser).Parse(0xc210000410, 0xc21001ee40, 0x6, 0x6)
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/web/server/parser/parser.go:16 +0xa2
github.com/smartystreets/goconvey/web/server/executor.(*Executor).parse(0xc210041740, 0xc21001ee40, 0x6, 0x6, 0x0)
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/web/server/executor/executor.go:47 +0xe7
github.com/smartystreets/goconvey/web/server/executor.(*Executor).ExecuteTests(0xc210041740, 0xc21001ee40, 0x6, 0x6, 0x0)
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/web/server/executor/executor.go:36 +0xb1
github.com/smartystreets/goconvey/web/server/contract.(*Monitor).executeTests(0xc21007cc60)
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/web/server/contract/monitor.go:45 +0x108
github.com/smartystreets/goconvey/web/server/contract.(*Monitor).Scan(0xc21007cc60)
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/web/server/contract/monitor.go:26 +0x63
github.com/smartystreets/goconvey/web/server/contract.(*Monitor).ScanForever(0xc21007cc60)
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/web/server/contract/monitor.go:18 +0xb5
created by main.main
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/goconvey.go:58 +0x1a0

goroutine 1 [IO wait]:
net.runtime_pollWait(0x662ac0, 0x72, 0x0)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc21004f450, 0x72, 0x660188, 0x23)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc21004f450, 0x23, 0x660188)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).accept(0xc21004f3f0, 0x31e020, 0x0, 0x660188, 0x23)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/fd_unix.go:382 +0x2c2
net.(*TCPListener).AcceptTCP(0xc210000440, 0x56d9b, 0x6a0ce0, 0x56d9b)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/tcpsock_posix.go:233 +0x47
net.(*TCPListener).Accept(0xc210000440, 0x662c70, 0xc210000e40, 0xc21005ce00, 0x0)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/tcpsock_posix.go:243 +0x27
net/http.(*Server).Serve(0xc21007af50, 0x661b20, 0xc210000440, 0x0, 0x0)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/http/server.go:1622 +0x91
net/http.(*Server).ListenAndServe(0xc21007af50, 0xc21007af50, 0x5)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/http/server.go:1612 +0xa0
net/http.ListenAndServe(0xc210000418, 0x5, 0x0, 0x0, 0x1, ...)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/http/server.go:1677 +0x6d
main.activateServer()
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/goconvey.go:86 +0x199
main.serveHTTP(0x6619c0, 0xc210041780)
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/goconvey.go:66 +0x3b
main.main()
    /Users/nbrennand/go_projects/src/github.com/smartystreets/goconvey/goconvey.go:60 +0x1ba

goroutine 4 [finalizer wait]:
runtime.park(0xe590, 0x558fa8, 0x557548)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/proc.c:1342 +0x66
runfinq()
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/mgc0.c:2279 +0x84
runtime.goexit()
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/proc.c:1394

goroutine 32 [IO wait]:
net.runtime_pollWait(0x662a18, 0x72, 0x0)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc210073840, 0x72, 0x660188, 0x23)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc210073840, 0x23, 0x660188)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc2100737e0, 0xc210109000, 0x1000, 0x1000, 0x0, ...)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc210000e40, 0xc210109000, 0x1000, 0x1000, 0x0, ...)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/net.go:122 +0xc5
net/http.(*liveSwitchReader).Read(0xc21005ce28, 0xc210109000, 0x1000, 0x1000, 0x6ddaf8, ...)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/http/server.go:204 +0xa5
io.(*LimitedReader).Read(0xc210083f80, 0xc210109000, 0x1000, 0x1000, 0x23541, ...)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/io/io.go:398 +0xbb
bufio.(*Reader).fill(0xc21008c060)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).ReadSlice(0xc21008c060, 0xc400a, 0x0, 0x0, 0x0, ...)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/bufio/bufio.go:274 +0x204
bufio.(*Reader).ReadLine(0xc21008c060, 0x0, 0x0, 0x0, 0x0, ...)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/bufio/bufio.go:305 +0x63
net/textproto.(*Reader).readLineSlice(0xc210071390, 0x657000, 0x1ddc20, 0x6ddce8, 0x23472, ...)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/textproto/reader.go:55 +0x61
net/textproto.(*Reader).ReadLine(0xc210071390, 0xc210037820, 0x0, 0xc21010b000, 0x0)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/textproto/reader.go:36 +0x27
net/http.ReadRequest(0xc21008c060, 0xc210037820, 0x0, 0x0)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/http/request.go:526 +0x88
net/http.(*conn).readRequest(0xc21005ce00, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/http/server.go:575 +0x1bb
net/http.(*conn).serve(0xc21005ce00)
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/http/server.go:1123 +0x3b4
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.2.2/libexec/src/pkg/net/http/server.go:1644 +0x28b
```

**Comment by Rogerzhao** [comment]
@mdwhatcott  Hello. I encounter similar problem. when using goconey on certain dir, works. Some other dir, always panic. 
2017/01/22 14:44:02 executor.go:69: Executor status: 'idle'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x1382c8]
