### ISSUE TITLE
Strange panic in test

### ISSUE THREAD

**Issue by on99** [smartystreets/goconvey#382]
I am using mac osx.

```
2016/01/10 10:09:42 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/examples/cellar/app
2016/01/10 10:09:42 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa
2016/01/10 10:09:42 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/examples/cellar
2016/01/10 10:09:42 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/examples/cellar/design
2016/01/10 10:09:42 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/examples/cellar/controllers
2016/01/10 10:09:42 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/goagen/gen_swagger
2016/01/10 10:09:42 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/goagen/gen_gen
2016/01/10 10:09:42 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/examples/cellar/swagger
2016/01/10 10:09:42 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/goagen/gen_client/test_/client/testapi-cli
2016/01/10 10:09:42 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/examples/cellar/client
2016/01/10 10:09:43 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/examples
2016/01/10 10:09:44 shell.go:102: Coverage output: ?   	github.com/raphael/goa/examples/cellar/design	[no test files]
2016/01/10 10:09:44 shell.go:104: Run without coverage
2016/01/10 10:09:44 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/goagen/gen_app
2016/01/10 10:09:48 shell.go:102: Coverage output: ?   	github.com/raphael/goa/examples/cellar/swagger	[no test files]
2016/01/10 10:09:48 shell.go:104: Run without coverage
2016/01/10 10:09:48 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/goagen/gen_client/test_/client
2016/01/10 10:09:48 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/testgoacodegen
2016/01/10 10:09:48 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/goagen/codegen
2016/01/10 10:09:49 shell.go:102: Coverage output: ?   	github.com/raphael/goa/examples/cellar/client	[no test files]
2016/01/10 10:09:49 shell.go:104: Run without coverage
2016/01/10 10:09:50 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/goagen/gen_main/goatest
2016/01/10 10:09:50 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/goagen/gen_schema
2016/01/10 10:09:51 shell.go:102: Coverage output: ?   	github.com/raphael/goa/examples/cellar/app	[no test files]
2016/01/10 10:09:51 shell.go:104: Run without coverage
2016/01/10 10:09:51 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/goagen/gen_js
2016/01/10 10:09:51 shell.go:102: Coverage output: ?   	github.com/raphael/goa/examples/cellar/controllers	[no test files]
2016/01/10 10:09:51 shell.go:104: Run without coverage
2016/01/10 10:09:51 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/design/dsl
2016/01/10 10:09:57 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/examples/cellar/schema
2016/01/10 10:09:57 shell.go:102: Coverage output: ?   	github.com/raphael/goa/examples/cellar/schema	[no test files]
2016/01/10 10:09:57 shell.go:104: Run without coverage
2016/01/10 10:09:58 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/design
2016/01/10 10:10:00 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/examples/cellar/js
2016/01/10 10:10:00 shell.go:102: Coverage output: ?   	github.com/raphael/goa/examples/cellar/js	[no test files]
2016/01/10 10:10:00 shell.go:104: Run without coverage
2016/01/10 10:10:01 coordinator.go:46: Executing concurrent tests: github.com/raphael/goa/goagen
2016/01/10 10:10:01 shell.go:102: Coverage output: === RUN   TestGenMain
Running Suite: GenGen Suite
===========================
Random Seed: 1452391796
Will run 2 of 2 specs

•panic: test timed out after 5s

goroutine 25 [running]:
testing.startAlarm.func1()
	/Users/d/workspace/go/src/testing/testing.go:703 +0x132
created by time.goFunc
	/Users/d/workspace/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x6c9430, 0x8ba520, 0x1, 0x1, 0xc820119301)
	/Users/d/workspace/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc82013dee8, 0x8c3400)
	/Users/d/workspace/go/src/testing/testing.go:494 +0x70
main.main()
	github.com/raphael/goa/goagen/gen_gen/_test/_testmain.go:104 +0x252

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/Users/d/workspace/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 14 [syscall]:
os/signal.loop()
	/Users/d/workspace/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/Users/d/workspace/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 24 [select, locked to thread]:
runtime.gopark(0x6c9aa0, 0xc820024728, 0x5ce738, 0x6, 0x6c9a18, 0x2)
	/Users/d/workspace/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820024728, 0x0, 0x18)
	/Users/d/workspace/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820024728)
	/Users/d/workspace/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/Users/d/workspace/go/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
	/Users/d/workspace/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 16 [syscall]:
syscall.Syscall6(0x7, 0x57da, 0xc820138bc4, 0x0, 0xc820488900, 0x0, 0x0, 0xc820138b98, 0xc820138ba0, 0xc820138b90)
	/Users/d/workspace/go/src/syscall/asm_darwin_amd64.s:41 +0x5
syscall.wait4(0x57da, 0xc820138bc4, 0x0, 0xc820488900, 0x90, 0x0, 0x0)
	/Users/d/workspace/go/src/syscall/zsyscall_darwin_amd64.go:34 +0x72
syscall.Wait4(0x57da, 0xc820138c0c, 0x0, 0xc820488900, 0xc82002cc40, 0x0, 0x0)
	/Users/d/workspace/go/src/syscall/syscall_bsd.go:129 +0x55
os.(*Process).wait(0xc82048aae0, 0x23, 0x0, 0x0)
	/Users/d/workspace/go/src/os/exec_unix.go:22 +0x105
os.(*Process).Wait(0xc82048aae0, 0x0, 0x0, 0x0)
	/Users/d/workspace/go/src/os/doc.go:45 +0x2d
os/exec.(*Cmd).Wait(0xc82009bcc0, 0x0, 0x0)
	/Users/d/workspace/go/src/os/exec/exec.go:380 +0x211
os/exec.(*Cmd).Run(0xc82009bcc0, 0x0, 0x0)
	/Users/d/workspace/go/src/os/exec/exec.go:258 +0x64
os/exec.(*Cmd).CombinedOutput(0xc82009bcc0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/d/workspace/go/src/os/exec/exec.go:424 +0x310
github.com/raphael/goa/goagen/meta.(*Generator).compile(0xc8201fd640, 0xc8201fd6c0, 0x3d, 0x0, 0x0, 0x0, 0x0)
	/Users/d/workspace/gopath/src/github.com/raphael/goa/goagen/meta/generator.go:203 +0x3b8
github.com/raphael/goa/goagen/meta.(*Generator).Generate(0xc8201fd640, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/d/workspace/gopath/src/github.com/raphael/goa/goagen/meta/generator.go:178 +0x4b8
github.com/raphael/goa/goagen/gen_gen.(*Command).Run(0xc82002cab8, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/raphael/goa/goagen/gen_gen/_test/_obj_test/command.go:52 +0x383
github.com/raphael/goa/goagen/gen_gen_test.glob.func1.2.2()
	/Users/d/workspace/gopath/src/github.com/raphael/goa/goagen/gen_gen/command_test.go:77 +0x2f
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc820253f80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/d/workspace/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/runner.go:109 +0x99
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc820253f80, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/d/workspace/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/runner.go:63 +0x9e
github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc8202ef480, 0xe74d20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/d/workspace/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:25 +0x50
github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc8201c4240, 0x0, 0xe74d20, 0xc82019dec0)
	/Users/d/workspace/gopath/src/github.com/onsi/ginkgo/internal/spec/spec.go:167 +0x590
github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc8201c4240, 0xe74d20, 0xc82019dec0)
	/Users/d/workspace/gopath/src/github.com/onsi/ginkgo/internal/spec/spec.go:118 +0xdc
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc8203b46c0, 0x6c9101)
	/Users/d/workspace/gopath/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:144 +0x1c0
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc8203b46c0, 0xc)
	/Users/d/workspace/gopath/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:61 +0x90
github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc82019e500, 0xe799d8, 0xc82033f5f0, 0x5d9050, 0xc, 0xc82043c230, 0x1, 0x1, 0xe79998, 0xc82019dec0, ...)
	/Users/d/workspace/gopath/src/github.com/onsi/ginkgo/internal/suite/suite.go:59 +0x269
github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0xe79820, 0xc82033f5f0, 0x5d9050, 0xc, 0xc820139e90, 0x1, 0x1, 0x3c85)
	/Users/d/workspace/gopath/src/github.com/onsi/ginkgo/ginkgo_dsl.go:207 +0x2da
github.com/onsi/ginkgo.RunSpecs(0xe79820, 0xc82033f5f0, 0x5d9050, 0xc, 0x609d5)
	/Users/d/workspace/gopath/src/github.com/onsi/ginkgo/ginkgo_dsl.go:188 +0x30a
github.com/raphael/goa/goagen/gen_gen_test.TestGenMain(0xc82033f5f0)
	/Users/d/workspace/gopath/src/github.com/raphael/goa/goagen/gen_gen/gen_gen_suite_test.go:12 +0x7c
testing.tRunner(0xc82033f5f0, 0x8ba520)
	/Users/d/workspace/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/Users/d/workspace/go/src/testing/testing.go:561 +0x86d

goroutine 50 [chan receive]:
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).registerForInterrupts(0xc8203b46c0)
	/Users/d/workspace/gopath/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:175 +0x1a3
created by github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
	/Users/d/workspace/gopath/src/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:56 +0x66

goroutine 53 [syscall]:
syscall.Syscall(0x3, 0x5, 0xc820164e00, 0x200, 0x0, 0x0, 0x117a9)
	/Users/d/workspace/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x5, 0xc820164e00, 0x200, 0x200, 0x3c85, 0x0, 0x0)
	/Users/d/workspace/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x5, 0xc820164e00, 0x200, 0x200, 0xc82002bce8, 0x0, 0x0)
	/Users/d/workspace/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc82002cc38, 0xc820164e00, 0x200, 0x200, 0xc820164e00, 0x0, 0x0)
	/Users/d/workspace/go/src/os/file_unix.go:211 +0x75
os.(*File).Read(0xc82002cc38, 0xc820164e00, 0x200, 0x200, 0x0, 0x0, 0x0)
	/Users/d/workspace/go/src/os/file.go:95 +0x8a
bytes.(*Buffer).ReadFrom(0xc820369960, 0xe74dc0, 0xc82002cc38, 0x0, 0x0, 0x0)
	/Users/d/workspace/go/src/bytes/buffer.go:173 +0x23f
io.copyBuffer(0xe74d48, 0xc820369960, 0xe74dc0, 0xc82002cc38, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/d/workspace/go/src/io/io.go:375 +0x180
io.Copy(0xe74d48, 0xc820369960, 0xe74dc0, 0xc82002cc38, 0x0, 0x0, 0x0)
	/Users/d/workspace/go/src/io/io.go:351 +0x64
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/Users/d/workspace/go/src/os/exec/exec.go:232 +0x8b
os/exec.(*Cmd).Start.func1(0xc82009bcc0, 0xc82048a880)
	/Users/d/workspace/go/src/os/exec/exec.go:340 +0x1d
created by os/exec.(*Cmd).Start
	/Users/d/workspace/go/src/os/exec/exec.go:341 +0x96d
exit status 2
FAIL	github.com/raphael/goa/goagen/gen_gen	5.053s
```

**Comment by mdwhatcott** [comment]
Do you have the latest goconvey executable? There used to be a default timeout set to 5 or 10 seconds, now it's set to zero by default.

https://github.com/smartystreets/goconvey/blob/master/goconvey.go#L42

**Comment by on99** [comment]
thx @mdwhatcott
