### ISSUE TITLE
Panic with index out of range when using symlinked go src dir

### ISSUE THREAD

**Issue by issmirnov** [smartystreets/goconvey#472]
Launching `goconvey` with the following config results in a panic.

- `GOPATH: ~/go/`
- symlink `~/go/src/example.com/project -> /Volumes/Data/Projects/go-proj`
- `pwd` is `~/go/src/example.com/project`

```
$ goconvey 
2017/02/12 22:45:06 goconvey.go:61: Initial configuration: [host: 127.0.0.1] [port: 8080] [poll: 250ms] [cover: true]
2017/02/12 22:45:06 tester.go:19: Now configured to test 10 packages concurrently.
2017/02/12 22:45:06 goconvey.go:192: Serving HTTP at: http://127.0.0.1:8080
2017/02/12 22:45:06 goconvey.go:105: Launching browser on 127.0.0.1:8080
2017/02/12 22:45:06 goconvey.go:113: 
2017/02/12 22:45:18 integration.go:97: Gathering folders for immediate execution...
2017/02/12 22:45:18 goconvey.go:118: Received request from watcher to execute tests...
2017/02/12 22:45:18 executor.go:69: Executor status: 'executing'
2017/02/12 22:45:18 executor.go:69: Executor status: 'idle'
panic: runtime error: index out of range

goroutine 18 [running]:
panic(0x32c9c0, 0xc42000c120)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.runTestOnUpdates(0xc42010e060, 0x503700, 0xc42010c100, 0x506800, 0xc42010c140)
	/Users/vania/go/src/github.com/smartystreets/goconvey/goconvey.go:121 +0x1d6
created by main.main
	/Users/vania/go/src/github.com/smartystreets/goconvey/goconvey.go:80 +0x642
```

Issue appears to be [L121](https://github.com/smartystreets/goconvey/blob/master/goconvey.go#L121) where we call `root := extractRoot(update, packages)`

Is there an easy fix for this? I know it's frowned upon, but for various reasons it fits my setup to have the traditional `GOPATH` and simply link in the relevant projects I'm working on.

**Comment by jcoutu-va** [comment]
This is breaking for me also.
