### ISSUE TITLE
Panic with latest Go development version

### ISSUE THREAD

**Issue by DenBeke** [smartystreets/goconvey#476]
GoConvey started to panic since yesterday on Travis for Go tip:

https://travis-ci.org/cadenzr/cadenzr/builds/224689364

```
--- FAIL: TestApi (1.00s)
panic: Convey operation made without context on goroutine stack.
Hint: Perhaps you meant to use `Convey(..., func(c C){...})` ? [recovered]
	panic: Convey operation made without context on goroutine stack.
Hint: Perhaps you meant to use `Convey(..., func(c C){...})` ? [recovered]
	panic: Convey operation made without context on goroutine stack.
Hint: Perhaps you meant to use `Convey(..., func(c C){...})` ?
goroutine 6 [running]:
testing.tRunner.func1(0xc4200def00)
	/home/travis/.gimme/versions/go/src/testing/testing.go:711 +0x256
panic(0x9444a0, 0xc4201c6c60)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:489 +0x25b
github.com/smartystreets/goconvey/convey.(*context).conveyInner.func2(0xc42001c5a0)
	/home/travis/gopath/src/github.com/smartystreets/goconvey/convey/context.go:232 +0x1bb
panic(0x9444a0, 0xc4201c6c60)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:489 +0x25b
github.com/smartystreets/goconvey/convey.conveyPanic(0x9edbf8, 0x78, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/smartystreets/goconvey/convey/context.go:20 +0x94
github.com/smartystreets/goconvey/convey.mustGetCurrentContext(0xeb55c0)
	/home/travis/gopath/src/github.com/smartystreets/goconvey/convey/context.go:52 +0x73
github.com/smartystreets/goconvey/convey.So(0x0, 0x0, 0x9f23a0, 0xc4201b8390, 0x1, 0x1)
	/home/travis/gopath/src/github.com/smartystreets/goconvey/convey/doc.go:125 +0x22
github.com/cadenzr/cadenzr.TestApi.func1(0xe8a0e0, 0xc42001c5a0)
	/home/travis/gopath/src/github.com/cadenzr/cadenzr/main_test.go:62 +0x287
github.com/smartystreets/goconvey/convey.(*context).conveyInner(0xc42001c5a0, 0x9d67b0, 0xa, 0x9f1f88)
	/home/travis/gopath/src/github.com/smartystreets/goconvey/convey/context.go:261 +0x162
github.com/smartystreets/goconvey/convey.rootConvey.func1()
	/home/travis/gopath/src/github.com/smartystreets/goconvey/convey/context.go:110 +0xfd
github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
	/home/travis/gopath/src/github.com/jtolds/gls/context.go:97 +0x460
github.com/jtolds/gls.EnsureGoroutineId.func1()
	/home/travis/gopath/src/github.com/jtolds/gls/gid.go:24 +0x31
github.com/jtolds/gls._m(0x0, 0xc4201361c0)
	/home/travis/gopath/src/github.com/jtolds/gls/stack_tags.go:74 +0x31
github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc4201361c0)
	/home/travis/gopath/src/github.com/jtolds/gls/stack_tags.go:54 +0x35
github.com/jtolds/gls.addStackTag(0x0, 0xc4201361c0)
	/home/travis/gopath/src/github.com/jtolds/gls/stack_tags.go:49 +0x3a
github.com/jtolds/gls.EnsureGoroutineId(0xc4201c2180)
	/home/travis/gopath/src/github.com/jtolds/gls/gid.go:24 +0xcd
github.com/jtolds/gls.(*ContextManager).SetValues(0xc420179550, 0xc4201c20c0, 0xc420136140)
	/home/travis/gopath/src/github.com/jtolds/gls/context.go:63 +0x177
github.com/smartystreets/goconvey/convey.rootConvey(0xc42003ded8, 0x3, 0x3)
	/home/travis/gopath/src/github.com/smartystreets/goconvey/convey/context.go:105 +0x2d6
github.com/smartystreets/goconvey/convey.Convey(0xc42003ded8, 0x3, 0x3)
	/home/travis/gopath/src/github.com/smartystreets/goconvey/convey/doc.go:75 +0x7e
github.com/cadenzr/cadenzr.TestApi(0xc4200def00)
	/home/travis/gopath/src/github.com/cadenzr/cadenzr/main_test.go:52 +0x106
testing.tRunner(0xc4200def00, 0x9f1ff0)
	/home/travis/.gimme/versions/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/home/travis/.gimme/versions/go/src/testing/testing.go:788 +0x2de
FAIL	github.com/cadenzr/cadenzr	1.011s
?   	github.com/cadenzr/cadenzr/config	[no test files]
```

My tests:

```go
func TestApi(t *testing.T) {

	configFile = "./main_test_config.json"

	go main()
	time.Sleep(time.Second * 1)

	Convey("Test login", t, func(c C) {

		resp, err := http.PostForm(
			endpoint+"/api/login",
			url.Values{
				"username": {"admin"},
				"password": {"test"},
			},
		)

		So(err, ShouldEqual, nil)    // line 62

                // ...
```

Any idea what might goes wrong on the latest development version of Go?
My tests work perfectly on Go 1.7 and 1.8.

The code is open source: https://github.com/cadenzr/cadenzr/blob/master/main_test.go

**Comment by issmirnov** [comment]
+1, same here: https://travis-ci.org/issmirnov/zap/jobs/226216301

**Comment by gdamore** [comment]
Any ideas as to how the stack backtrace might have been changed to affect this?  This is definitely breaking testing with GoConvey against tip on travis... which is unfortunate.

**Comment by ththvseo** [comment]
somebody should build a test-case and report this here: https://github.com/jtolds/gls/issues

**Comment by jtolds** [comment]
Thanks for the report @ththvseo! Should be fixed now.

**Comment by jtolds** [comment]
Someone want to confirm their Travis builds pass again and we can close this?

**Comment by issmirnov** [comment]
Confirmed, relaunched the build of my project and it worked: https://travis-ci.org/issmirnov/zap/builds/226216297

**Comment by jtolds** [comment]
Okay, cool, just need @DenBeke or a GoConvey dev to mark this closed. Thanks again for letting me know!

**Comment by DenBeke** [comment]
Same here, Travis is all green again ;)
Thanks, @jtolds and @ththvseo!

**Comment by lucaswxp** [comment]
Was this solved? Still getting this issue on go version go1.9 darwin/amd64

```
panic: Convey operation made without context on goroutine stack.
Hint: Perhaps you meant to use `Convey(..., func(c C){...})` ? [recovered]
	panic: Convey operation made without context on goroutine stack.
Hint: Perhaps you meant to use `Convey(..., func(c C){...})` ? [recovered]
	panic: Convey operation made without context on goroutine stack.
Hint: Perhaps you meant to use `Convey(..., func(c C){...})` ?

goroutine 6 [running]:
testing.tRunner.func1(0xc4201240f0)
	/usr/local/Cellar/go/1.9/libexec/src/testing/testing.go:711 +0x2d2
panic(0x12f9000, 0xc4204d14d0)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
reduza/vendor/github.com/smartystreets/goconvey/convey.(*context).conveyInner.func2(0xc4200702a0)
	/Users/lucaswxp/src/reduza/vendor/github.com/smartystreets/goconvey/convey/context.go:232 +0x1c8
panic(0x12f9000, 0xc4204d14d0)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
reduza/vendor/github.com/smartystreets/goconvey/convey.conveyPanic(0x1373640, 0x78, 0x0, 0x0, 0x0)
	/Users/lucaswxp/src/reduza/vendor/github.com/smartystreets/goconvey/convey/context.go:20 +0xca
reduza/vendor/github.com/smartystreets/goconvey/convey.mustGetCurrentContext(0xc420088680)
	/Users/lucaswxp/src/reduza/vendor/github.com/smartystreets/goconvey/convey/context.go:52 +0x73
reduza/vendor/github.com/smartystreets/goconvey/convey.So(0x0, 0x0, 0x1378660, 0xc420244f60, 0x1, 0x1)
	/Users/lucaswxp/src/reduza/vendor/github.com/smartystreets/goconvey/convey/doc.go:125 +0x22
reduza/crawlers.TestShouldCrawlB2W.func1()
	/Users/lucaswxp/src/reduza/crawlers/B2W_test.go:14 +0xf8
reduza/vendor/github.com/smartystreets/goconvey/convey.parseAction.func1(0x14f44e0, 0xc4200702a0)
	/Users/lucaswxp/src/reduza/vendor/github.com/smartystreets/goconvey/convey/discovery.go:80 +0x24
reduza/vendor/github.com/smartystreets/goconvey/convey.(*context).conveyInner(0xc4200702a0, 0x1360d61, 0xa, 0xc420052ea0)
	/Users/lucaswxp/src/reduza/vendor/github.com/smartystreets/goconvey/convey/context.go:261 +0x162
reduza/vendor/github.com/smartystreets/goconvey/convey.rootConvey.func1()
	/Users/lucaswxp/src/reduza/vendor/github.com/smartystreets/goconvey/convey/context.go:110 +0xec
reduza/vendor/github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
	/Users/lucaswxp/src/reduza/vendor/github.com/jtolds/gls/context.go:97 +0x463
reduza/vendor/github.com/jtolds/gls.EnsureGoroutineId.func1()
	/Users/lucaswxp/src/reduza/vendor/github.com/jtolds/gls/gid.go:24 +0x31
reduza/vendor/github.com/jtolds/gls._m(0x0, 0xc4200ee4e0)
	/Users/lucaswxp/src/reduza/vendor/github.com/jtolds/gls/stack_tags.go:74 +0x31
reduza/vendor/github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc4200ee4e0)
	/Users/lucaswxp/src/reduza/vendor/github.com/jtolds/gls/stack_tags.go:54 +0x35
reduza/vendor/github.com/jtolds/gls.addStackTag(0x0, 0xc4200ee4e0)
	/Users/lucaswxp/src/reduza/vendor/github.com/jtolds/gls/stack_tags.go:49 +0x3a
reduza/vendor/github.com/jtolds/gls.EnsureGoroutineId(0xc420011200)
	/Users/lucaswxp/src/reduza/vendor/github.com/jtolds/gls/gid.go:24 +0xc9
reduza/vendor/github.com/jtolds/gls.(*ContextManager).SetValues(0xc420052e20, 0xc4200111a0, 0xc4200ee4a0)
	/Users/lucaswxp/src/reduza/vendor/github.com/jtolds/gls/context.go:63 +0x177
reduza/vendor/github.com/smartystreets/goconvey/convey.rootConvey(0xc42003e738, 0x3, 0x3)
	/Users/lucaswxp/src/reduza/vendor/github.com/smartystreets/goconvey/convey/context.go:105 +0x2d6
reduza/vendor/github.com/smartystreets/goconvey/convey.Convey(0xc42003e738, 0x3, 0x3)
	/Users/lucaswxp/src/reduza/vendor/github.com/smartystreets/goconvey/convey/doc.go:75 +0x7a
reduza/crawlers.TestShouldCrawlB2W(0xc4201240f0)
	/Users/lucaswxp/src/reduza/crawlers/B2W_test.go:11 +0xb7
testing.tRunner(0xc4201240f0, 0x1378548)
	/usr/local/Cellar/go/1.9/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.9/libexec/src/testing/testing.go:789 +0x2de
```

**Comment by ththvseo** [comment]
@lucaswxp:
your log shows that you are using vendored versions, which are likely outdated.
make sure to update github.com/jtolds/gls ...

**Comment by lucaswxp** [comment]
@ththvseo So a simple "go get -u github.com/jtolds/gls" should solve it? I did it, and the problem continues. Also tried to update goconvey. Any idea?

**Comment by ththvseo** [comment]
@lucaswxp:
refer to the documentation for the build setuo you are using. (you omitted any details, so we can only guess.)
the issue is definitively solved in the current version of github.com/jtolds/gls, and debugging your build setup is off-topic here.

your build is using code from `/Users/lucaswxp/src/reduza/vendor/github.com/jtolds/gls`, which is very likely NOT the code installed by "go get"... (which will be directly in `$GOPATH/src/github.com/...` refer to the details of your build setup, or maybe just try "rm -fr /Users/lucaswxp/src/reduza/vendor/github.com/jtolds/gls` to either force using the code from GOPATH, or trigger an error that will lead you to how to update the vendored code.

**Comment by lucaswxp** [comment]
@ththvseo Ohh, now I understood what you meant. I'm just starting with go, thank you!
