### ISSUE TITLE
ERROR in web server: index out of range 

### ISSUE THREAD

**Issue by titanxxh** [smartystreets/goconvey#502]
2017/10/31 11:22:06 executor.go:69: Executor status: 'idle'
panic: runtime error: index out of range

goroutine 6 [running]:
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).recordTestMetadata(0xc042030f50)
        D:/goproject/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:104 +0x1b7
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).processTestOutput(0xc042030f50)
        D:/goproject/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:86 +0xa5
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).separateTestFunctionsAndMetadata(0xc042030f50)
        D:/goproject/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:53 +0x88
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).parse(0xc042030f50)
        D:/goproject/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:44 +0x32
github.com/smartystreets/goconvey/web/server/parser.ParsePackageResults(0xc04221e660, 0xc042440000, 0x46ea)
        D:/goproject/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:18 +0x54
github.com/smartystreets/goconvey/web/server/parser.(*Parser).Parse(0xc042004098, 0xc042268200, 0x12, 0x20)
        D:/goproject/src/github.com/smartystreets/goconvey/web/server/parser/parser.go:16 +0x2ae
github.com/smartystreets/goconvey/web/server/executor.(*Executor).parse(0xc04210ca80, 0xc042268200, 0x12, 0x20, 0xffffffffffffffff)
        D:/goproject/src/github.com/smartystreets/goconvey/web/server/executor/executor.go:47 +0xe6
github.com/smartystreets/goconvey/web/server/executor.(*Executor).ExecuteTests(0xc04210ca80, 0xc042268200, 0x12, 0x20, 0x0)
        D:/goproject/src/github.com/smartystreets/goconvey/web/server/executor/executor.go:36 +0xaf
main.runTestOnUpdates(0xc042113620, 0x95e840, 0xc04210ca80, 0x9619c0, 0xc04210cac0)
        D:/goproject/src/github.com/smartystreets/goconvey/goconvey.go:120 +0x13d
created by main.main
        D:/goproject/src/github.com/smartystreets/goconvey/goconvey.go:80 +0x647

**Comment by jonaz** [comment]
i have similar issue!
```
2017/11/01 07:46:23 goconvey.go:61: Initial configuration: [host: 127.0.0.1] [port: 8080] [poll: 250ms] [cover: true]
2017/11/01 07:46:23 tester.go:19: Now configured to test 10 packages concurrently.
2017/11/01 07:46:23 goconvey.go:192: Serving HTTP at: http://127.0.0.1:8080
2017/11/01 07:46:23 goconvey.go:105: Launching browser on 127.0.0.1:8080
2017/11/01 07:46:23 integration.go:122: File system state modified, publishing current folders... 0 9040565748
2017/11/01 07:46:23 goconvey.go:118: Received request from watcher to execute tests...
2017/11/01 07:46:23 executor.go:69: Executor status: 'executing'
2017/11/01 07:46:23 coordinator.go:46: Executing concurrent tests: stash.fortnox.local/fnx/storage-service.git/storage-service/e2e
2017/11/01 07:46:24 goconvey.go:113: ATTENTION: default value of option force_s3tc_enable overridden by environment.
Created new window in existing browser session.

2017/11/01 07:46:25 executor.go:69: Executor status: 'idle'
panic: runtime error: index out of range

goroutine 6 [running]:
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).recordTestMetadata(0xc420107500)
	/home/jonaz/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:104 +0x1b0
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).processTestOutput(0xc420107500)
	/home/jonaz/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:86 +0x9a
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).separateTestFunctionsAndMetadata(0xc420107500)
	/home/jonaz/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:53 +0x45
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).parse(0xc420107500)
	/home/jonaz/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:44 +0x2b
github.com/smartystreets/goconvey/web/server/parser.ParsePackageResults(0xc42019c480, 0xc42025e000, 0x5caf)
	/home/jonaz/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:18 +0x4d
github.com/smartystreets/goconvey/web/server/parser.(*Parser).Parse(0xc42000e0a0, 0xc4201860b0, 0x1, 0x1)
	/home/jonaz/go/src/github.com/smartystreets/goconvey/web/server/parser/parser.go:16 +0x29f
github.com/smartystreets/goconvey/web/server/executor.(*Executor).parse(0xc420060840, 0xc4201860b0, 0x1, 0x1, 0xffffffffffffffff)
	/home/jonaz/go/src/github.com/smartystreets/goconvey/web/server/executor/executor.go:47 +0xc8
github.com/smartystreets/goconvey/web/server/executor.(*Executor).ExecuteTests(0xc420060840, 0xc4201860b0, 0x1, 0x1, 0x0)
	/home/jonaz/go/src/github.com/smartystreets/goconvey/web/server/executor/executor.go:36 +0xa8
main.runTestOnUpdates(0xc4200245a0, 0x997e00, 0xc420060840, 0x99b0c0, 0xc420060880)
	/home/jonaz/go/src/github.com/smartystreets/goconvey/goconvey.go:120 +0x15d
created by main.main

```

**Comment by nicwest** [comment]
this occurrs for me when I have something that gives `---` at the start of the line for example:

```go
// foo.go 
package foo

func bar() map[string]string {
	return map[string]string{
		"foo": "bar",
	}
}
```
```go
// foo_test.go
package foo

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestFunction(t *testing.T) {
	assert.Equal(t, map[string]string{"sad": "face"}, bar())
}
```
`go test` generates an output that contains a diff of elements:

```
◤ ~/g/s/g/n/foo go test
--- FAIL: TestFunction (0.00s)
        Error Trace:    foo_test.go:10
	Error:      	Not equal: 
	            	expected: map[string]string{"sad":"face"}
	            	actual: map[string]string{"foo":"bar"}
	            	
	            	Diff:
	            	--- Expected
	            	+++ Actual
	            	@@ -1,3 +1,3 @@
	            	 (map[string]string) (len=1) {
	            	- (string) (len=3) "sad": (string) (len=4) "face"
	            	+ (string) (len=3) "foo": (string) (len=3) "bar"
	            	 }
FAIL
exit status 1
FAIL	github.com/nicwest/foo	0.004s
```
`goconvey` panics:

```
◤ ~/g/s/g/n/foo goconvey
2017/12/14 14:44:58 goconvey.go:61: Initial configuration: [host: 127.0.0.1] [port: 8080] [poll: 250ms] [cover: true]
2017/12/14 14:44:58 tester.go:19: Now configured to test 10 packages concurrently.
2017/12/14 14:44:58 goconvey.go:192: Serving HTTP at: http://127.0.0.1:8080
2017/12/14 14:44:58 goconvey.go:105: Launching browser on 127.0.0.1:8080
2017/12/14 14:44:58 integration.go:122: File system state modified, publishing current folders... 0 3026525565
2017/12/14 14:44:58 goconvey.go:118: Received request from watcher to execute tests...
2017/12/14 14:44:58 executor.go:69: Executor status: 'executing'
2017/12/14 14:44:58 coordinator.go:46: Executing concurrent tests: github.com/nicwest/foo
2017/12/14 14:44:59 goconvey.go:113: 
this is the line --- FAIL: TestFunction (0.00s)
this is the line --- Expected
2017/12/14 14:44:59 executor.go:69: Executor status: 'idle'
panic: runtime error: index out of range

goroutine 3 [running]:
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).recordTestMetadata(0xc4202520e0)
	/home/nic/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:105 +0x22b
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).processTestOutput(0xc4202520e0)
	/home/nic/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:86 +0x9a
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).separateTestFunctionsAndMetadata(0xc4202520e0)
	/home/nic/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:53 +0x45
github.com/smartystreets/goconvey/web/server/parser.(*outputParser).parse(0xc4202520e0)
	/home/nic/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:44 +0x2b
github.com/smartystreets/goconvey/web/server/parser.ParsePackageResults(0xc4201a6180, 0xc420270000, 0x2b5)
	/home/nic/go/src/github.com/smartystreets/goconvey/web/server/parser/packageParser.go:18 +0x4d
github.com/smartystreets/goconvey/web/server/parser.(*Parser).Parse(0xc42000e010, 0xc42019c028, 0x1, 0x1)
	/home/nic/go/src/github.com/smartystreets/goconvey/web/server/parser/parser.go:16 +0x29f
github.com/smartystreets/goconvey/web/server/executor.(*Executor).parse(0xc420062140, 0xc42019c028, 0x1, 0x1, 0xffffffffffffffff)
	/home/nic/go/src/github.com/smartystreets/goconvey/web/server/executor/executor.go:47 +0xc8
github.com/smartystreets/goconvey/web/server/executor.(*Executor).ExecuteTests(0xc420062140, 0xc42019c028, 0x1, 0x1, 0x0)
	/home/nic/go/src/github.com/smartystreets/goconvey/web/server/executor/executor.go:36 +0xa8
main.runTestOnUpdates(0xc420144060, 0x997e00, 0xc420062140, 0x99b0c0, 0xc420062180)
	/home/nic/go/src/github.com/smartystreets/goconvey/goconvey.go:120 +0x15d
created by main.main
	/home/nic/go/src/github.com/smartystreets/goconvey/goconvey.go:80 +0x616
```
this is the line that is causing the panic:
https://github.com/smartystreets/goconvey/blob/e5b2b7c9111590d019a696c7800593f666e1a7f4/web/server/parser/packageParser.go#L104

and it's because the 
```
	            	--- Expected
```
line from the test out put is trying to be interpreted as a `--- FAIL: xyz` or `--- PASS: xyz` line there is only one space and so the split only creates a slice with 2 elements.
