### ISSUE TITLE
Panic on Running Tests

### ISSUE THREAD

**Issue by jpoles1** [smartystreets/goconvey#520]
Tests do not run when application is initialized. The following panic occurs when the "run tests" button is pressed.

`panic: runtime error: index out of range

goroutine 18 [running]:
main.extractRoot(...)
        /mnt/c/Users/jpole/Development/go/src/github.com/smartystreets/goconvey/goconvey.go:136
main.runTestOnUpdates(0xc4201120c0, 0x997e00, 0xc420108100, 0x99b0c0, 0xc420108140)
        /mnt/c/Users/jpole/Development/go/src/github.com/smartystreets/goconvey/goconvey.go:121 +0x181
created by main.main
        /mnt/c/Users/jpole/Development/go/src/github.com/smartystreets/goconvey/goconvey.go:80 +0x616`

**Comment by btm6084** [comment]
I came to report the same issue. Seems to be a problem with output parsing. Seems to require '---' as the first non-whitespace string in a given line, followed by a space, followed by anything else. 


I wrote this simple test, which is enough to replicate:

```
package main

import (
	"fmt"
	"testing"
)

func TestGoConveyPanic(t *testing.T) {
	fmt.Println(\`--- Panic\`)
}
```
```
func TestGoConveyPanic(t *testing.T) {
	fmt.Println(\`        --- Panic\`)
}
```
```
fmt.Println(\`Panic
 	--- Panic\`)
```
```
fmt.Println(\`No Panic
a 	--- No Panic\`)
```

**Comment by ciokan** [comment]
I have the same issue...
