### ISSUE TITLE
Panic In Some Environments

### ISSUE THREAD

**Issue by CannibalVox** [smartystreets/goconvey#568]
I'm concerned that this is actually my fault, but I can't figure out how.  I'm receiving a panic attempting to print the stacktrace for test failures, but not when I'm running tests in a debug environment.  The issue seems to be that the runtime package is missing when I run `goconvey` or `go test ./...` from console.  I'm not clear why.

```
  * /Users/baynhas/projects/accountservice/server/integration_test.go
  Line 2054:
  Expected: nil
  Actual:   '%!v(PANIC=Format method: runtime error: invalid memory address or nil pointer dereference)'
  goroutine 34 [running]:
        /Users/baynhas/go/pkg/mod/github.com/smartystreets/goconvey@v0.0.0-20190330032615-68dc04aab96a/convey/reporting/reports.go:143 +0x6d
        /Users/baynhas/go/pkg/mod/github.com/smartystreets/goconvey@v0.0.0-20190330032615-68dc04aab96a/convey/reporting/reports.go:103 +0x6d
        /Users/baynhas/go/pkg/mod/github.com/smartystreets/goconvey@v0.0.0-20190330032615-68dc04aab96a/convey/context.go:176 +0xe3
        /Users/baynhas/go/pkg/mod/github.com/smartystreets/goconvey@v0.0.0-20190330032615-68dc04aab96a/convey/doc.go:125 +0x63
  gitlab.com/wotc/dps/accountservice.git/server.testDeleteGame()
        /Users/baynhas/projects/accountservice/server/integration_test.go:2054 +0xf1
  gitlab.com/wotc/dps/accountservice.git/server.TestSurface.func3()
        /Users/baynhas/projects/accountservice/server/integration_test.go:360 +0x552
        /Users/baynhas/go/pkg/mod/github.com/smartystreets/goconvey@v0.0.0-20190330032615-68dc04aab96a/convey/discovery.go:80 +0x24
        /Users/baynhas/go/pkg/mod/github.com/smartystreets/goconvey@v0.0.0-20190330032615-68dc04aab96a/convey/context.go:261 +0x154
        /Users/baynhas/go/pkg/mod/github.com/smartystreets/goconvey@v0.0.0-20190330032615-68dc04aab96a/convey/context.go:110 +0xf1
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
        /Users/baynhas/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId.func1()
        /Users/baynhas/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0x2e
  github.com/jtolds/gls._m(0x0, 0xc0002721c0)
        /Users/baynhas/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:108 +0x31
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc0002721c0)
        /Users/baynhas/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:56 +0x35
  github.com/jtolds/gls.addStackTag(...)
        /Users/baynhas/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc0002741e0)
        /Users/baynhas/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0xd6
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0000b50b0, 0xc000274180, 0xc000272180)
        /Users/baynhas/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x14b
        /Users/baynhas/go/pkg/mod/github.com/smartystreets/goconvey@v0.0.0-20190330032615-68dc04aab96a/convey/context.go:105 +0x22b
        /Users/baynhas/go/pkg/mod/github.com/smartystreets/goconvey@v0.0.0-20190330032615-68dc04aab96a/convey/doc.go:75 +0xbf
  gitlab.com/wotc/dps/accountservice.git/server.TestSurface(0xc00019e200)
        /Users/baynhas/projects/accountservice/server/integration_test.go:81 +0x33c
  testing.tRunner(0xc00019e200, 0x19af9a0)
        /usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:865 +0xc0
  created by testing.(*T).Run
        /usr/local/Cellar/go/1.12/libexec/src/testing/testing.go:916 +0x357
```

I believe `68dc04aab96a` is the latest go version, so this is not a version mismatch.  I apologize if this has an obvious solution, I'm kind of at the end of my rope here.

**Comment by CannibalVox** [comment]
I was right, it was my fault!  A custom error library wasn't handling inlines in the stack trace very well.
