### ISSUE TITLE
Tests fail on latest Go 1.12 version

### ISSUE THREAD

**Issue by powerman** [smartystreets/goconvey#573]
I have same issue on my usual system with 1.12.5, but just in case here is clean way to reproduce using docker and latest version (GOPATH mode):
```
$ docker run -i -t --rm golang:1.12.6-stretch
root@89a03957ccc0:/go# mkdir -p /go/src/github.com/smartystreets         
root@89a03957ccc0:/go# cd /go/src/github.com/smartystreets 
root@89a03957ccc0:/go/src/github.com/smartystreets# git clone https://github.com/smartystreets/goconvey
Cloning into 'goconvey'...
remote: Enumerating objects: 7044, done.
remote: Total 7044 (delta 0), reused 0 (delta 0), pack-reused 7044
Receiving objects: 100% (7044/7044), 3.79 MiB | 2.06 MiB/s, done.
Resolving deltas: 100% (3789/3789), done.
root@89a03957ccc0:/go/src/github.com/smartystreets# cd goconvey/
root@89a03957ccc0:/go/src/github.com/smartystreets/goconvey# go get ./...
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
	see 'go help modules'
root@89a03957ccc0:/go/src/github.com/smartystreets/goconvey# go test ./...
?   	github.com/smartystreets/goconvey	[no test files]
ok  	github.com/smartystreets/goconvey/convey	0.042s
ok  	github.com/smartystreets/goconvey/convey/gotest	0.025s [no tests to run]
ok  	github.com/smartystreets/goconvey/convey/reporting	0.026s
ok  	github.com/smartystreets/goconvey/examples	0.056s
ok  	github.com/smartystreets/goconvey/web/server/api	0.244s
ok  	github.com/smartystreets/goconvey/web/server/contract	0.023s [no tests to run]
ok  	github.com/smartystreets/goconvey/web/server/executor	0.038s
ok  	github.com/smartystreets/goconvey/web/server/messaging	0.003s [no tests to run]
ok  	github.com/smartystreets/goconvey/web/server/parser	0.015s
ok  	github.com/smartystreets/goconvey/web/server/system	1.910s
...
3 total assertions

...
6 total assertions

...
9 total assertions

...
12 total assertions

...
15 total assertions

...
18 total assertions

...
21 total assertions

...
24 total assertions

...
27 total assertions

...
30 total assertions

...
33 total assertions

...
36 total assertions

...
39 total assertions

...
42 total assertions

......
48 total assertions

......
54 total assertions

..
56 total assertions

.
57 total assertions

x...x.x...x
Failures:

  * /go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go 
  Line 82:
  Expected: '1'
  Actual:   '0'
  (Should be equal)
  goroutine 28 [running]:
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3.1()
  	/go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go:82 +0x1c6
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/src/github.com/jtolds/gls/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000f5200)
  	/go/src/github.com/jtolds/gls/gid.go:19 +0x108
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0000805b0, 0xc0000f51a0, 0xc0001043c0)
  	/go/src/github.com/jtolds/gls/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3()
  	/go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go:74 +0x223
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/src/github.com/jtolds/gls/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId.func1()
  	/go/src/github.com/jtolds/gls/gid.go:24 +0x2e
  github.com/jtolds/gls._m(0x0, 0xc0001043a0)
  	/go/src/github.com/jtolds/gls/stack_tags.go:108 +0x31
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc0001043a0)
  	/go/src/github.com/jtolds/gls/stack_tags.go:56 +0x35
  github.com/jtolds/gls.addStackTag(...)
  	/go/src/github.com/jtolds/gls/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000f5050)
  	/go/src/github.com/jtolds/gls/gid.go:24 +0xd6
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0000805b0, 0xc0000f4ff0, 0xc000104360)
  	/go/src/github.com/jtolds/gls/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher(0xc0000ce900)
  	/go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go:66 +0x64c
  testing.tRunner(0xc0000ce900, 0x5f6b28)
  	/usr/local/go/src/testing/testing.go:865 +0xc0
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:916 +0x35a
  

  * /go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go 
  Line 113:
  Expected: '1'
  Actual:   '0'
  (Should be equal)
  goroutine 28 [running]:
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3.3()
  	/go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go:113 +0x247
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/src/github.com/jtolds/gls/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000f5a10)
  	/go/src/github.com/jtolds/gls/gid.go:19 +0x108
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0000805b0, 0xc0000f59b0, 0xc000104860)
  	/go/src/github.com/jtolds/gls/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3()
  	/go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go:101 +0x469
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/src/github.com/jtolds/gls/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId.func1()
  	/go/src/github.com/jtolds/gls/gid.go:24 +0x2e
  github.com/jtolds/gls._m(0x0, 0xc0001043a0)
  	/go/src/github.com/jtolds/gls/stack_tags.go:108 +0x31
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc0001043a0)
  	/go/src/github.com/jtolds/gls/stack_tags.go:56 +0x35
  github.com/jtolds/gls.addStackTag(...)
  	/go/src/github.com/jtolds/gls/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000f5050)
  	/go/src/github.com/jtolds/gls/gid.go:24 +0xd6
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0000805b0, 0xc0000f4ff0, 0xc000104360)
  	/go/src/github.com/jtolds/gls/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher(0xc0000ce900)
  	/go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go:66 +0x64c
  testing.tRunner(0xc0000ce900, 0x5f6b28)
  	/usr/local/go/src/testing/testing.go:865 +0xc0
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:916 +0x35a
  

  * /go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go 
  Line 130:
  Expected: '2'
  Actual:   '1'
  (Should be equal)
  goroutine 28 [running]:
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3.4()
  	/go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go:130 +0x2d7
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/src/github.com/jtolds/gls/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000f5e00)
  	/go/src/github.com/jtolds/gls/gid.go:19 +0x108
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0000805b0, 0xc0000f5da0, 0xc000104b60)
  	/go/src/github.com/jtolds/gls/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3()
  	/go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go:117 +0x5a1
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/src/github.com/jtolds/gls/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId.func1()
  	/go/src/github.com/jtolds/gls/gid.go:24 +0x2e
  github.com/jtolds/gls._m(0x0, 0xc0001043a0)
  	/go/src/github.com/jtolds/gls/stack_tags.go:108 +0x31
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc0001043a0)
  	/go/src/github.com/jtolds/gls/stack_tags.go:56 +0x35
  github.com/jtolds/gls.addStackTag(...)
  	/go/src/github.com/jtolds/gls/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000f5050)
  	/go/src/github.com/jtolds/gls/gid.go:24 +0xd6
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0000805b0, 0xc0000f4ff0, 0xc000104360)
  	/go/src/github.com/jtolds/gls/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher(0xc0000ce900)
  	/go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go:66 +0x64c
  testing.tRunner(0xc0000ce900, 0x5f6b28)
  	/usr/local/go/src/testing/testing.go:865 +0xc0
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:916 +0x35a
  

  * /go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go 
  Line 197:
  Expected: '2'
  Actual:   '1'
  (Should be equal)
  goroutine 28 [running]:
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3.8()
  	/go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go:197 +0x246
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/src/github.com/jtolds/gls/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId(0xc00025c720)
  	/go/src/github.com/jtolds/gls/gid.go:19 +0x108
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0000805b0, 0xc00025c6c0, 0xc00009a780)
  	/go/src/github.com/jtolds/gls/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3()
  	/go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go:180 +0xa28
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/src/github.com/jtolds/gls/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId.func1()
  	/go/src/github.com/jtolds/gls/gid.go:24 +0x2e
  github.com/jtolds/gls._m(0x0, 0xc0001043a0)
  	/go/src/github.com/jtolds/gls/stack_tags.go:108 +0x31
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc0001043a0)
  	/go/src/github.com/jtolds/gls/stack_tags.go:56 +0x35
  github.com/jtolds/gls.addStackTag(...)
  	/go/src/github.com/jtolds/gls/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000f5050)
  	/go/src/github.com/jtolds/gls/gid.go:24 +0xd6
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc0000805b0, 0xc0000f4ff0, 0xc000104360)
  	/go/src/github.com/jtolds/gls/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher(0xc0000ce900)
  	/go/src/github.com/smartystreets/goconvey/web/server/watch/integration_test.go:66 +0x64c
  testing.tRunner(0xc0000ce900, 0x5f6b28)
  	/usr/local/go/src/testing/testing.go:865 +0xc0
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:916 +0x35a
  


68 total assertions

--- FAIL: TestWatcher (3.04s)
    integration_test.go:27: 2019/06/23 09:24:27.295823 integration.go:101: Stopping the watcher...
        2019/06/23 09:24:27.296184 integration.go:97: Gathering folders for immediate execution...
        2019/06/23 09:24:27.296657 integration.go:122: File system state modified, publishing current folders... 0 3122563951
        2019/06/23 09:24:27.301271 integration.go:101: Stopping the watcher...
        2019/06/23 09:24:27.301584 integration.go:75: Ignoring specified folders
        2019/06/23 09:24:27.301614 integration.go:163: Currently ignored folders: map[/tmp/goconvey722450985/integration_testing/sub:{}]
        2019/06/23 09:24:27.303128 integration.go:82: Reinstating specified folders
        2019/06/23 09:24:27.304711 integration.go:101: Stopping the watcher...
        2019/06/23 09:24:27.305040 integration.go:70: Adjusting root...
        2019/06/23 09:24:27.307447 integration.go:70: Adjusting root...
        2019/06/23 09:24:27.307915 integration.go:122: File system state modified, publishing current folders... 0 3122563951
        2019/06/23 09:24:27.310322 integration.go:101: Stopping the watcher...
        2019/06/23 09:24:27.311318 integration.go:106: Unrecognized command from server: UNKNOWN INSTRUCTION
        2019/06/23 09:24:27.311556 integration.go:122: File system state modified, publishing current folders... 0 3122563951
        2019/06/23 09:24:27.316393 integration.go:101: Stopping the watcher...
        2019/06/23 09:24:27.316970 integration.go:122: File system state modified, publishing current folders... 0 3122563951
        2019/06/23 09:24:28.320231 integration.go:122: File system state modified, publishing current folders... 3122563951 3122563952
        2019/06/23 09:24:29.322793 integration.go:101: Stopping the watcher...
        2019/06/23 09:24:29.323050 integration.go:89: Pausing watcher...
        2019/06/23 09:24:29.324196 integration.go:93: Resuming watcher...
        2019/06/23 09:24:29.324468 integration.go:122: File system state modified, publishing current folders... 0 3122563952
        2019/06/23 09:24:29.325518 integration.go:101: Stopping the watcher...
        2019/06/23 09:24:29.325697 integration.go:89: Pausing watcher...
        2019/06/23 09:24:30.328622 integration.go:93: Resuming watcher...
        2019/06/23 09:24:30.328910 integration.go:122: File system state modified, publishing current folders... 0 3122563954
        2019/06/23 09:24:30.329997 integration.go:101: Stopping the watcher...
        
FAIL
FAIL	github.com/smartystreets/goconvey/web/server/watch	3.058s
ok  	github.com/smartystreets/goconvey/web/server/watch/integration_testing	0.008s [no tests to run]
ok  	github.com/smartystreets/goconvey/web/server/watch/integration_testing/sub	0.054s
root@89a03957ccc0:/go/src/github.com/smartystreets/goconvey# 
```

**Comment by powerman** [comment]
Same issue (modules mode):
```
$ docker run -i -t --rm golang:1.12.6-stretch
root@244bc0b2c35d:/go# cd /
root@244bc0b2c35d:/# git clone https://github.com/smartystreets/goconvey
Cloning into 'goconvey'...
remote: Enumerating objects: 7044, done.
remote: Total 7044 (delta 0), reused 0 (delta 0), pack-reused 7044
Receiving objects: 100% (7044/7044), 3.79 MiB | 2.40 MiB/s, done.
Resolving deltas: 100% (3789/3789), done.
root@244bc0b2c35d:/# cd goconvey/
root@244bc0b2c35d:/goconvey# go test ./...
go: finding github.com/gopherjs/gopherjs v0.0.0-20181017120253-0766667cb4d1
go: finding github.com/smartystreets/assertions v0.0.0-20180927180507-b2de0cb4f26d
go: finding github.com/jtolds/gls v4.20.0+incompatible
go: finding golang.org/x/tools v0.0.0-20190328211700-ab21143f2384
go: finding golang.org/x/net v0.0.0-20190311183353-d8887717615a
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: downloading github.com/jtolds/gls v4.20.0+incompatible
go: downloading golang.org/x/tools v0.0.0-20190328211700-ab21143f2384
go: downloading github.com/smartystreets/assertions v0.0.0-20180927180507-b2de0cb4f26d
go: extracting github.com/jtolds/gls v4.20.0+incompatible
go: extracting github.com/smartystreets/assertions v0.0.0-20180927180507-b2de0cb4f26d
go: extracting golang.org/x/tools v0.0.0-20190328211700-ab21143f2384
?   	github.com/smartystreets/goconvey	[no test files]
ok  	github.com/smartystreets/goconvey/convey	0.085s
ok  	github.com/smartystreets/goconvey/convey/gotest	0.006s [no tests to run]
ok  	github.com/smartystreets/goconvey/convey/reporting	0.031s
ok  	github.com/smartystreets/goconvey/examples	0.043s
ok  	github.com/smartystreets/goconvey/web/server/api	0.256s
ok  	github.com/smartystreets/goconvey/web/server/contract	0.024s [no tests to run]
ok  	github.com/smartystreets/goconvey/web/server/executor	0.005s
ok  	github.com/smartystreets/goconvey/web/server/messaging	0.062s [no tests to run]
ok  	github.com/smartystreets/goconvey/web/server/parser	0.009s
ok  	github.com/smartystreets/goconvey/web/server/system	2.396s
...
3 total assertions

...
6 total assertions

...
9 total assertions

...
12 total assertions

...
15 total assertions

...
18 total assertions

...
21 total assertions

...
24 total assertions

...
27 total assertions

...
30 total assertions

...
33 total assertions

...
36 total assertions

...
39 total assertions

...
42 total assertions

......
48 total assertions

......
54 total assertions

..
56 total assertions

.
57 total assertions

x.....x...x
Failures:

  * /goconvey/web/server/watch/integration_test.go 
  Line 82:
  Expected: '1'
  Actual:   '0'
  (Should be equal)
  goroutine 15 [running]:
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3.1()
  	/goconvey/web/server/watch/integration_test.go:82 +0x1c6
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000cf020)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:19 +0x108
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc000050530, 0xc0000cefc0, 0xc0000dc3a0)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3()
  	/goconvey/web/server/watch/integration_test.go:74 +0x223
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId.func1()
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0x2e
  github.com/jtolds/gls._m(0x0, 0xc0000dc380)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:108 +0x31
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc0000dc380)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:56 +0x35
  github.com/jtolds/gls.addStackTag(...)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000cee70)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0xd6
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc000050530, 0xc0000cee10, 0xc0000dc340)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher(0xc00009e900)
  	/goconvey/web/server/watch/integration_test.go:66 +0x64c
  testing.tRunner(0xc00009e900, 0x5dd4e0)
  	/usr/local/go/src/testing/testing.go:865 +0xc0
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:916 +0x35a
  

  * /goconvey/web/server/watch/integration_test.go 
  Line 129:
  Expected: '3'
  Actual:   '2'
  (Should be equal)
  goroutine 15 [running]:
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3.4()
  	/goconvey/web/server/watch/integration_test.go:129 +0x22c
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000cfa10)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:19 +0x108
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc000050530, 0xc0000cf9b0, 0xc0000dca60)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3()
  	/goconvey/web/server/watch/integration_test.go:117 +0x5a1
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId.func1()
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0x2e
  github.com/jtolds/gls._m(0x0, 0xc0000dc380)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:108 +0x31
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc0000dc380)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:56 +0x35
  github.com/jtolds/gls.addStackTag(...)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000cee70)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0xd6
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc000050530, 0xc0000cee10, 0xc0000dc340)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher(0xc00009e900)
  	/goconvey/web/server/watch/integration_test.go:66 +0x64c
  testing.tRunner(0xc00009e900, 0x5dd4e0)
  	/usr/local/go/src/testing/testing.go:865 +0xc0
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:916 +0x35a
  

  * /goconvey/web/server/watch/integration_test.go 
  Line 197:
  Expected: '2'
  Actual:   '1'
  (Should be equal)
  goroutine 15 [running]:
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3.8()
  	/goconvey/web/server/watch/integration_test.go:197 +0x246
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId(0xc000288a20)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:19 +0x108
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc000050530, 0xc0002889c0, 0xc0002ed280)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher.func3()
  	/goconvey/web/server/watch/integration_test.go:180 +0xa28
  github.com/jtolds/gls.(*ContextManager).SetValues.func1(0x0)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:97 +0x40d
  github.com/jtolds/gls.EnsureGoroutineId.func1()
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0x2e
  github.com/jtolds/gls._m(0x0, 0xc0000dc380)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:108 +0x31
  github.com/jtolds/gls.github_com_jtolds_gls_markS(0x0, 0xc0000dc380)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:56 +0x35
  github.com/jtolds/gls.addStackTag(...)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/stack_tags.go:49
  github.com/jtolds/gls.EnsureGoroutineId(0xc0000cee70)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/gid.go:24 +0xd6
  github.com/jtolds/gls.(*ContextManager).SetValues(0xc000050530, 0xc0000cee10, 0xc0000dc340)
  	/go/pkg/mod/github.com/jtolds/gls@v4.20.0+incompatible/context.go:63 +0x14b
  github.com/smartystreets/goconvey/web/server/watch.TestWatcher(0xc00009e900)
  	/goconvey/web/server/watch/integration_test.go:66 +0x64c
  testing.tRunner(0xc00009e900, 0x5dd4e0)
  	/usr/local/go/src/testing/testing.go:865 +0xc0
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:916 +0x35a
  


68 total assertions

--- FAIL: TestWatcher (3.06s)
    integration_test.go:27: 2019/06/23 09:29:20.279589 integration.go:101: Stopping the watcher...
        2019/06/23 09:29:20.280107 integration.go:97: Gathering folders for immediate execution...
        2019/06/23 09:29:20.280527 integration.go:122: File system state modified, publishing current folders... 0 3122564537
        2019/06/23 09:29:20.287074 integration.go:101: Stopping the watcher...
        2019/06/23 09:29:20.288010 integration.go:122: File system state modified, publishing current folders... 0 3122564537
        2019/06/23 09:29:20.289526 integration.go:75: Ignoring specified folders
        2019/06/23 09:29:20.289556 integration.go:163: Currently ignored folders: map[/tmp/goconvey420495484/integration_testing/sub:{}]
        2019/06/23 09:29:20.296714 integration.go:82: Reinstating specified folders
        2019/06/23 09:29:20.296958 integration.go:101: Stopping the watcher...
        2019/06/23 09:29:20.297221 integration.go:70: Adjusting root...
        2019/06/23 09:29:20.297382 integration.go:70: Adjusting root...
        2019/06/23 09:29:20.297692 integration.go:101: Stopping the watcher...
        2019/06/23 09:29:20.298009 integration.go:106: Unrecognized command from server: UNKNOWN INSTRUCTION
        2019/06/23 09:29:20.298218 integration.go:122: File system state modified, publishing current folders... 0 3122564537
        2019/06/23 09:29:20.304378 integration.go:101: Stopping the watcher...
        2019/06/23 09:29:20.305009 integration.go:122: File system state modified, publishing current folders... 0 3122564537
        2019/06/23 09:29:21.325612 integration.go:122: File system state modified, publishing current folders... 3122564537 3122564538
        2019/06/23 09:29:22.325901 integration.go:101: Stopping the watcher...
        2019/06/23 09:29:22.326263 integration.go:89: Pausing watcher...
        2019/06/23 09:29:22.327361 integration.go:93: Resuming watcher...
        2019/06/23 09:29:22.327601 integration.go:122: File system state modified, publishing current folders... 0 3122564538
        2019/06/23 09:29:22.328669 integration.go:101: Stopping the watcher...
        2019/06/23 09:29:22.328839 integration.go:89: Pausing watcher...
        2019/06/23 09:29:23.338908 integration.go:93: Resuming watcher...
        2019/06/23 09:29:23.339258 integration.go:122: File system state modified, publishing current folders... 0 3122564540
        2019/06/23 09:29:23.340374 integration.go:101: Stopping the watcher...
        
FAIL
FAIL	github.com/smartystreets/goconvey/web/server/watch	3.095s
ok  	github.com/smartystreets/goconvey/web/server/watch/integration_testing	0.014s [no tests to run]
ok  	github.com/smartystreets/goconvey/web/server/watch/integration_testing/sub	0.058s
root@244bc0b2c35d:/goconvey# 
```

**Comment by powerman** [comment]
I'd like to update my PRs and related tests but blocked by this issue. :disappointed:
